# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: windows-latest

variables:
  projectFolder: "."
  buildOutputFolder: "dist"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName:
      "npm install"

      # Download secure file from azure library
  - task: DownloadSecureFile@1
    inputs:
      secureFile: ".env"

  # Copy the .env file
  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Agent.TempDirectory)"
      contents: "**/*.env"
      targetFolder: "$(projectFolder)"
      cleanTargetFolder: false

  - script: |
      npm run build
    displayName: "npm build"
